logging:
  level:
    root: info
    pl.futurecollars.invoicing: error
    org.springframework: error


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  profiles:
    active: dev