on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start MongoDb
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: 4.4
      - name: Test with Gradle
        run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start MongoDb
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: 4.4

      - name: Build with Gradle
        run: ./gradlew build

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d


